# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/items
accept: application/json
Content-Type: application/json

###

POST http://127.0.0.1:8000/items
accept: application/json
Content-Type: application/json

{
  "title": "Название товара",
  "description": "Описание товара.",
  "price": 100
}

###

PUT http://127.0.0.1:8000/items/651241e4410f3f40d434c1c2
accept: application/json
Content-Type: application/json

{
  "price": 1000000
}

###

DELETE http://127.0.0.1:8000/items/651241e4410f3f40d434c1c2
accept: application/json
Content-Type: application/json

###

GET http://127.0.0.1:8000/users
accept: application/json
Content-Type: application/json

###

POST http://127.0.0.1:8000/users/register/
accept: application/json
Content-Type: application/json

{
  "username": "Buyer",
  "email": "buyer@example.com",
  "password": "bbb"
}

###

PUT http://127.0.0.1:8000/users/Buyer
accept: application/json
Content-Type: application/json

{
  "username": "EditBuyer"
}

###

DELETE http://127.0.0.1:8000/users/EditBuyer
accept: application/json
Content-Type: application/json

###

GET http://127.0.0.1:8000/orders/api
accept: application/json
Content-Type: application/json

###

POST http://127.0.0.1:8000/orders/
accept: application/json
Content-Type: application/json

{
  "username": "123"
}

###

PUT http://127.0.0.1:8000/orders/651232e9bd9afc18f2c5685b
accept: application/json
Content-Type: application/json

{
  "username": "NewBuyer"
}

###

DELETE http://127.0.0.1:8000/orders/65122931d576a27de29256ca
accept: application/json
Content-Type: application/json

###


