# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/items
accept: application/json
Content-Type: application/json

###

POST http://127.0.0.1:8000/items/
accept: application/json
Content-Type: application/json

{
  "title": "Название товара",
  "description": "Описание товара.",
  "price": 100
}

###

PUT http://127.0.0.1:8000/items/650aec25c4be8c8950481fe2
accept: application/json
Content-Type: application/json

{
  "price": 1185
}

###

DELETE http://127.0.0.1:8000/items/650d4894c2fdac61fa88f506
accept: application/json
Content-Type: application/json

###

GET http://127.0.0.1:8000/users
accept: application/json
Content-Type: application/json

###

POST http://127.0.0.1:8000/users/register/
accept: application/json
Content-Type: application/json

{
  "username": "Person",
  "email": "person@example.com",
  "password": "qwerty"
}

###

PUT http://127.0.0.1:8000/users/VeryVeryVeryVery
accept: application/json
Content-Type: application/json

{
  "username": "Very",
  "email": "end@address.com",
  "password": "samesame"
}

###

DELETE http://127.0.0.1:8000/users/Very
accept: application/json
Content-Type: application/json

###

GET http://127.0.0.1:8000/orders/api
accept: application/json
Content-Type: application/json

###

POST http://127.0.0.1:8000/orders/
accept: application/json
Content-Type: application/json

{
  "username": "123"
}
