# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/items
accept: application/json
Content-Type: application/json

###

POST http://127.0.0.1:8000/items
accept: application/json
Content-Type: application/json

{
  "title": "Название товара",
  "description": "Описание товара.",
  "price": 100
}

###

PUT http://127.0.0.1:8000/items/651241e4410f3f40d434c1c2
accept: application/json
Content-Type: application/json

{
  "price": 1000000
}

###

DELETE http://127.0.0.1:8000/items/651241e4410f3f40d434c1c2
accept: application/json
Content-Type: application/json

###

GET http://127.0.0.1:8000/users
accept: application/json
Content-Type: application/json

###

POST http://127.0.0.1:8000/users/register/
accept: application/json
Content-Type: application/json

{
  "username": "Buyer",
  "email": "buyer@example.com",
  "password": "bbb"
}

###

PUT http://127.0.0.1:8000/users/Buyer
accept: application/json
Content-Type: application/json

{
  "username": "EditBuyer"
}

###

DELETE http://127.0.0.1:8000/users/EditBuyer
accept: application/json
Content-Type: application/json

###

GET http://127.0.0.1:8000/orders/api
accept: application/json
Content-Type: application/json

###

POST http://127.0.0.1:8000/orders
accept: application/json
Content-Type: application/json

{
  "item_id": "650ae86f6da5afad1ea0345c",
  "username": "admin"
}

###

PUT http://127.0.0.1:8000/orders/65124cbaa8b361d5a9b02832
accept: application/json
Content-Type: application/json

{
  "username": "NewBuyer"
}

###

DELETE http://127.0.0.1:8000/orders/6512483edb0bdf1c1947c812
accept: application/json
Content-Type: application/json

###


